-- ============================================================
-- Migration: 20260224000001_content_pipeline.sql
-- Description: Content pipeline tables — content_drafts,
--              page_audits, local_occasions, citation_source_intelligence
-- Specs: 04c-SOV-ENGINE.md, Doc 19 (Autopilot), Doc 17 (Content Grader),
--        Doc 16 (Occasion Engine), Doc 18 (Citation Intelligence)
-- Breaking: No — new tables only.
-- Depends on: 20260218000000_initial_schema.sql (organizations, locations, model_provider enum)
-- Note: trigger_id on content_drafts is UUID NULL (no hard FK) — references
--       competitor_intercepts, target_queries, or local_occasions by convention only.
-- ============================================================

-- ── content_drafts ────────────────────────────────────────────
-- Generated by Autopilot when a gap is detected.
-- Trigger types: competitor_gap, occasion, prompt_missing, first_mover
-- Human approval required before publish (no auto-publish).

CREATE TABLE IF NOT EXISTS public.content_drafts (
  id              UUID          PRIMARY KEY DEFAULT uuid_generate_v4(),
  org_id          UUID          NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  location_id     UUID          REFERENCES public.locations(id) ON DELETE SET NULL,

  -- What triggered this draft
  trigger_type    VARCHAR(50)   NOT NULL
    CHECK (trigger_type IN ('competitor_gap', 'occasion', 'prompt_missing', 'first_mover', 'manual')),
  trigger_id      UUID          NULL,   -- FK to competitor_intercepts, target_queries, or local_occasions

  -- Content
  draft_title     TEXT          NOT NULL,
  draft_content   TEXT          NOT NULL,
  target_prompt   TEXT          NULL,   -- The AI query this content is designed to win
  content_type    VARCHAR(50)   NOT NULL
    CHECK (content_type IN ('faq_page', 'occasion_page', 'blog_post', 'landing_page', 'gbp_post')),

  -- AEO scoring (calculated at draft time)
  aeo_score       INTEGER       NULL,   -- 0–100

  -- Workflow state
  status          VARCHAR(20)   NOT NULL DEFAULT 'draft'
    CHECK (status IN ('draft', 'approved', 'published', 'rejected', 'archived')),
  human_approved  BOOLEAN       NOT NULL DEFAULT FALSE,

  -- Publish tracking
  published_url   TEXT          NULL,
  published_at    TIMESTAMPTZ   NULL,
  approved_at     TIMESTAMPTZ   NULL,

  created_at      TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_content_drafts_org_status
  ON public.content_drafts(org_id, status);

CREATE INDEX IF NOT EXISTS idx_content_drafts_trigger
  ON public.content_drafts(trigger_type, trigger_id);

CREATE TRIGGER set_updated_at_content_drafts
  BEFORE UPDATE ON public.content_drafts
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

ALTER TABLE public.content_drafts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "org_isolation_select" ON public.content_drafts
  FOR SELECT USING (org_id = public.current_user_org_id());

CREATE POLICY "org_isolation_insert" ON public.content_drafts
  FOR INSERT WITH CHECK (org_id = public.current_user_org_id());

CREATE POLICY "org_isolation_update" ON public.content_drafts
  FOR UPDATE USING (org_id = public.current_user_org_id());


-- ── page_audits ───────────────────────────────────────────────
-- Site-wide AEO content grading (not just menu items).
-- Covers homepage, about, FAQ, events, occasion pages.
-- One row per URL per audit run.

CREATE TABLE IF NOT EXISTS public.page_audits (
  id              UUID          PRIMARY KEY DEFAULT uuid_generate_v4(),
  org_id          UUID          NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  location_id     UUID          REFERENCES public.locations(id) ON DELETE SET NULL,

  page_url        TEXT          NOT NULL,
  page_type       VARCHAR(50)   NOT NULL
    CHECK (page_type IN ('homepage', 'menu', 'about', 'faq', 'events', 'occasion', 'other')),

  -- Scoring components (0–100 each)
  aeo_readability_score     INTEGER  NULL,
  answer_first_score        INTEGER  NULL,  -- Does first sentence answer intent?
  schema_completeness_score INTEGER  NULL,  -- Required schema types present?
  faq_schema_present        BOOLEAN  NULL,

  -- Composite score (weighted average of above)
  overall_score    INTEGER  NULL,

  -- Structured fix list: [{issue: string, fix: string, impact_points: number}]
  recommendations  JSONB    NULL,

  last_audited_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  created_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_page_audits_org_url
  ON public.page_audits(org_id, page_url);

CREATE UNIQUE INDEX IF NOT EXISTS idx_page_audits_org_url_unique
  ON public.page_audits(org_id, page_url);

ALTER TABLE public.page_audits ENABLE ROW LEVEL SECURITY;

CREATE POLICY "org_isolation_select" ON public.page_audits
  FOR SELECT USING (org_id = public.current_user_org_id());


-- ── local_occasions ───────────────────────────────────────────
-- Reference table — shared across all tenants (no org_id).
-- Managed by LocalVector (not editable by tenants).
-- Powers the Occasion Module seasonal scheduler.

CREATE TABLE IF NOT EXISTS public.local_occasions (
  id                UUID          PRIMARY KEY DEFAULT uuid_generate_v4(),
  name              VARCHAR(100)  NOT NULL UNIQUE,   -- "Valentine's Day"
  occasion_type     VARCHAR(50)   NOT NULL
    CHECK (occasion_type IN ('holiday', 'celebration', 'recurring', 'seasonal')),
  trigger_days_before  INTEGER    NOT NULL DEFAULT 28,  -- alert N days before peak
  annual_date          VARCHAR(10) NULL,  -- 'MM-DD' format (e.g., '02-14' for Valentine's)

  -- Queries AI models answer with this occasion context
  -- [{query: string, category: QueryCategory}]
  peak_query_patterns  JSONB      NOT NULL DEFAULT '[]',

  -- Which business categories this occasion is relevant for
  -- ["restaurant", "hookah lounge", "bar", "event venue"]
  relevant_categories  JSONB      NOT NULL DEFAULT '[]',

  is_active  BOOLEAN  NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- No RLS — this is a shared reference table, read-only for tenants


-- ── citation_source_intelligence ──────────────────────────────
-- Stores which platforms AI cites for each category+city combination.
-- Written by the Citation Intelligence cron (Doc 18).
-- Powers the Citation Gap Finder feature.

CREATE TABLE IF NOT EXISTS public.citation_source_intelligence (
  id                UUID          PRIMARY KEY DEFAULT uuid_generate_v4(),

  -- Segment dimensions
  business_category VARCHAR(100)  NOT NULL,   -- 'hookah lounge'
  city              VARCHAR(100)  NOT NULL,
  state             VARCHAR(50)   NOT NULL,

  -- The platform being cited
  platform          VARCHAR(50)   NOT NULL,   -- 'yelp', 'tripadvisor', 'reddit', 'google', 'facebook'

  -- How frequently this platform is cited for this category+city
  -- 0.0 = never cited, 1.0 = cited in every AI response sampled
  citation_frequency  FLOAT       NOT NULL CHECK (citation_frequency BETWEEN 0 AND 1),

  -- Sample data
  sample_query      TEXT          NULL,       -- One example query that produced this citation
  sample_size       INTEGER       NOT NULL DEFAULT 1,   -- # queries this measurement is based on

  model_provider    model_provider NOT NULL,
  measured_at       TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

  -- One row per category+city+platform+model combination
  UNIQUE(business_category, city, state, platform, model_provider)
);

CREATE INDEX IF NOT EXISTS idx_citation_category_city
  ON public.citation_source_intelligence(business_category, city, state);

-- No RLS — this is aggregate market intelligence, not tenant-specific data
-- Accessible via service role only; surfaced to tenants through API (Doc 05 Section 7.3)
